In [2]:
import numpy as np
import pandas as pd

In [3]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [4]:
names.shape

(7,)

In [31]:
data = np.random.randn(7,4)
data

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 2.2920405 ,  1.49644672, -0.32962582,  0.46345931],
       [ 1.00652877,  0.7943395 ,  1.24938991,  0.18863573],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853],
       [ 0.3672694 ,  1.28227224, -1.26068774, -0.64285887],
       [-3.11966609,  0.36972541, -0.73163798, -0.13362597],
       [-0.83960874, -0.15338499,  0.06020363,  1.11077885]])

In [32]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [33]:
data[names == 'bob']

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853]])

In [34]:
names_bool = np.array([True, False, False,  True, False, False, False])
names_bool

array([ True, False, False,  True, False, False, False])

In [35]:
names_bool == False

array([False,  True,  True, False,  True,  True,  True])

In [36]:
~names_bool

array([False,  True,  True, False,  True,  True,  True])

In [37]:
~names_bool

array([False,  True,  True, False,  True,  True,  True])

In [58]:
a = pd.Series(names_bool)
a

0     True
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [59]:
a.values

array([ True, False, False,  True, False, False, False])

In [60]:
a.index

RangeIndex(start=0, stop=7, step=1)

In [61]:
data[a]

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853]])

In [62]:
data[a.values]

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853]])

In [63]:
a

0     True
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [64]:
data[a.values]

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853]])

In [65]:
~a

0    False
1     True
2     True
3    False
4     True
5     True
6     True
dtype: bool

In [66]:
b = a.astype(int)
b

0    1
1    0
2    0
3    1
4    0
5    0
6    0
dtype: int64

In [67]:
~b

0   -2
1   -1
2   -1
3   -2
4   -1
5   -1
6   -1
dtype: int64

In [68]:
1-b

0    0
1    1
2    1
3    0
4    1
5    1
6    1
dtype: int64

In [69]:
c = a.astype('bool')
c

0     True
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [70]:
data[~names_bool]

array([[ 2.2920405 ,  1.49644672, -0.32962582,  0.46345931],
       [ 1.00652877,  0.7943395 ,  1.24938991,  0.18863573],
       [ 0.3672694 ,  1.28227224, -1.26068774, -0.64285887],
       [-3.11966609,  0.36972541, -0.73163798, -0.13362597],
       [-0.83960874, -0.15338499,  0.06020363,  1.11077885]])

In [71]:
data[(names == 'bob') | (names == 'joe')]

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 2.2920405 ,  1.49644672, -0.32962582,  0.46345931],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853],
       [-3.11966609,  0.36972541, -0.73163798, -0.13362597],
       [-0.83960874, -0.15338499,  0.06020363,  1.11077885]])

In [72]:
data

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 2.2920405 ,  1.49644672, -0.32962582,  0.46345931],
       [ 1.00652877,  0.7943395 ,  1.24938991,  0.18863573],
       [ 0.65429437,  0.98518629, -0.16591096, -1.05834853],
       [ 0.3672694 ,  1.28227224, -1.26068774, -0.64285887],
       [-3.11966609,  0.36972541, -0.73163798, -0.13362597],
       [-0.83960874, -0.15338499,  0.06020363,  1.11077885]])

In [73]:
data[0,1]

1.1331496624223056

In [74]:
data[0]

array([-1.22747865,  1.13314966, -2.326951  , -0.71969786])

In [75]:
data[[0,1]]

array([[-1.22747865,  1.13314966, -2.326951  , -0.71969786],
       [ 2.2920405 ,  1.49644672, -0.32962582,  0.46345931]])

In [76]:
data[:,[0,1]]

array([[-1.22747865,  1.13314966],
       [ 2.2920405 ,  1.49644672],
       [ 1.00652877,  0.7943395 ],
       [ 0.65429437,  0.98518629],
       [ 0.3672694 ,  1.28227224],
       [-3.11966609,  0.36972541],
       [-0.83960874, -0.15338499]])

In [41]:
z = data[(names == 'bob') & (names == 'joe')]

In [42]:
z.shape

(0, 4)

In [43]:
data > 0

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False,  True, False,  True],
       [False,  True, False, False],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [44]:
data[data<0] = 0
data

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.35262175e-01],
       [7.56438096e-01, 2.11356034e+00, 5.56330826e-01, 0.00000000e+00],
       [4.95998068e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.41972196e+00, 0.00000000e+00, 1.57254705e-03],
       [0.00000000e+00, 6.06328909e-01, 0.00000000e+00, 0.00000000e+00],
       [9.56398196e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.29250064e+00, 0.00000000e+00, 1.19407078e+00, 0.00000000e+00]])

In [45]:
data

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.35262175e-01],
       [7.56438096e-01, 2.11356034e+00, 5.56330826e-01, 0.00000000e+00],
       [4.95998068e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.41972196e+00, 0.00000000e+00, 1.57254705e-03],
       [0.00000000e+00, 6.06328909e-01, 0.00000000e+00, 0.00000000e+00],
       [9.56398196e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.29250064e+00, 0.00000000e+00, 1.19407078e+00, 0.00000000e+00]])

In [46]:
data = np.random.randn(7,4)
data

array([[-0.16037093,  1.77901553,  1.10809707, -1.01926701],
       [ 0.77379772, -0.2275199 ,  0.86335311,  1.23346106],
       [-0.55364619,  2.45445181, -0.02299863,  1.63237237],
       [ 0.59477051, -0.04961244, -0.5904889 ,  0.37960061],
       [ 0.26723087,  2.16578896, -0.7436363 , -2.49696488],
       [ 0.78697872,  1.42788415, -0.60884899, -1.32216317],
       [-0.45591425,  0.63899523, -1.29867259, -1.48649303]])

In [47]:
data[[4,3,2,1]]

array([[ 0.26723087,  2.16578896, -0.7436363 , -2.49696488],
       [ 0.59477051, -0.04961244, -0.5904889 ,  0.37960061],
       [-0.55364619,  2.45445181, -0.02299863,  1.63237237],
       [ 0.77379772, -0.2275199 ,  0.86335311,  1.23346106]])

In [48]:
df = pd.DataFrame(data, columns=('0','1','2','3'))

In [49]:
df

0         1         2         3
0 -0.160371  1.779016  1.108097 -1.019267
1  0.773798 -0.227520  0.863353  1.233461
2 -0.553646  2.454452 -0.022999  1.632372
3  0.594771 -0.049612 -0.590489  0.379601
4  0.267231  2.165789 -0.743636 -2.496965
5  0.786979  1.427884 -0.608849 -1.322163
6 -0.455914  0.638995 -1.298673 -1.486493

In [50]:
df[['3','2']]

3         2
0 -1.019267  1.108097
1  1.233461  0.863353
2  1.632372 -0.022999
3  0.379601 -0.590489
4 -2.496965 -0.743636
5 -1.322163 -0.608849
6 -1.486493 -1.298673

In [51]:
arr = np.arange(16).reshape(2,2,4)

In [52]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [53]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [54]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [55]:
arr.transpose([1,0,2])

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [56]:
arr.transpose([2,0,1])

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [57]:
arr.transpose([0,2,1])

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [58]:
arr.transpose([0,2,1]).reshape(16,)

array([ 0,  4,  1,  5,  2,  6,  3,  7,  8, 12,  9, 13, 10, 14, 11, 15])

In [59]:
len(arr)

2

In [60]:
len(df)

7

In [61]:
df.shape

(7, 4)

In [62]:
np.__version__

'1.17.2'

In [63]:
pd.__version__

'0.25.1'

# MultiIndex

In [64]:
data = pd.Series(np.random.randn(9), 
                 index=[['a','a','a','b','b','c','c','d','d'],
                        [1,2,3,1,3,1,2,2,3]])
data

a  1    0.292105
   2    0.433550
   3    0.234659
b  1    1.415248
   3    0.229077
c  1   -0.668288
   2   -0.794307
d  2    0.158479
   3   -0.182796
dtype: float64

In [65]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [66]:
data['b']

1    1.415248
3    0.229077
dtype: float64

In [70]:
data['b':'d']

b  1    1.415248
   3    0.229077
c  1   -0.668288
   2   -0.794307
d  2    0.158479
   3   -0.182796
dtype: float64

In [72]:
data.loc[['b','d']]

b  1    1.415248
   3    0.229077
d  2    0.158479
   3   -0.182796
dtype: float64

In [73]:
data.loc[:,2]

a    0.433550
c   -0.794307
d    0.158479
dtype: float64

In [74]:
data.loc[:,[1,3]]

a  1    0.292105
   3    0.234659
b  1    1.415248
   3    0.229077
c  1   -0.668288
d  3   -0.182796
dtype: float64

# unstack

In [76]:
data

a  1    0.292105
   2    0.433550
   3    0.234659
b  1    1.415248
   3    0.229077
c  1   -0.668288
   2   -0.794307
d  2    0.158479
   3   -0.182796
dtype: float64

In [75]:
data.unstack()

1         2         3
a  0.292105  0.433550  0.234659
b  1.415248       NaN  0.229077
c -0.668288 -0.794307       NaN
d       NaN  0.158479 -0.182796

In [77]:
data.unstack().stack()

a  1    0.292105
   2    0.433550
   3    0.234659
b  1    1.415248
   3    0.229077
c  1   -0.668288
   2   -0.794307
d  2    0.158479
   3   -0.182796
dtype: float64

# MultiIndex on DataFrame

In [82]:
df = pd.DataFrame(np.arange(15).reshape((5,3)),
                 index = [['a','a','a','b','b'],[1,2,3,1,2]],
                 columns=[['Ohio', 'Ohio', 'Colorado'],
                         ['green','red','green']])
df

Ohio     Colorado
    green red    green
a 1     0   1        2
  2     3   4        5
  3     6   7        8
b 1     9  10       11
  2    12  13       14

In [84]:
df = pd.DataFrame(np.arange(12).reshape((4,3)),
                 index = [['a','a','b','b'],[1,2,1,2]],
                 columns=[['Ohio', 'Ohio', 'Colorado'],
                         ['green','red','green']])
df

Ohio     Colorado
    green red    green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [86]:
df = pd.DataFrame(np.arange(18).reshape((6,3)),
                 index = [['a','a','a','b','b','c'],[1,2,3,1,2,1]],
                 columns=[['Ohio', 'Ohio', 'Colorado'],
                         ['green','red','green']])
df

Ohio     Colorado
    green red    green
a 1     0   1        2
  2     3   4        5
  3     6   7        8
b 1     9  10       11
  2    12  13       14
c 1    15  16       17

In [87]:
df['Ohio']

green  red
a 1      0    1
  2      3    4
  3      6    7
b 1      9   10
  2     12   13
c 1     15   16

In [92]:
df.loc['a']

Ohio     Colorado
  green red    green
1     0   1        2
2     3   4        5
3     6   7        8

In [103]:
df

Ohio     Colorado
    green red    green
a 1     0   1        2
  2     3   4        5
  3     6   7        8
b 1     9  10       11
  2    12  13       14
c 1    15  16       17

In [131]:
df.loc[(:,2)] # use df.query instead

SyntaxError: invalid syntax (<ipython-input-131-1b4c074401a0>, line 1)

In [104]:
df.reset_index()

level_0 level_1  Ohio     Colorado
                  green red    green
0       a       1     0   1        2
1       a       2     3   4        5
2       a       3     6   7        8
3       b       1     9  10       11
4       b       2    12  13       14
5       c       1    15  16       17

In [114]:
df[('Ohio', 'green')]

a  1     0
   2     3
   3     6
b  1     9
   2    12
c  1    15
Name: (Ohio, green), dtype: int64

In [117]:
df.loc[('a',1)]

Ohio      green    0
          red      1
Colorado  green    2
Name: (a, 1), dtype: int64

In [123]:
df.index.names = ['k1','k2']
df

Ohio     Colorado
      green red    green
k1 k2                   
a  1      0   1        2
   2      3   4        5
   3      6   7        8
b  1      9  10       11
   2     12  13       14
c  1     15  16       17

In [127]:
df.index.name = 'keys'
df

Ohio     Colorado
      green red    green
k1 k2                   
a  1      0   1        2
   2      3   4        5
   3      6   7        8
b  1      9  10       11
   2     12  13       14
c  1     15  16       17

In [129]:
df.query('k2==2')

Ohio     Colorado
      green red    green
k1 k2                   
a  2      3   4        5
b  2     12  13       14

In [132]:
df

Ohio     Colorado
      green red    green
k1 k2                   
a  1      0   1        2
   2      3   4        5
   3      6   7        8
b  1      9  10       11
   2     12  13       14
c  1     15  16       17

In [134]:
df.loc['a']

Ohio     Colorado
   green red    green
k2                   
1      0   1        2
2      3   4        5
3      6   7        8

In [135]:
df.swaplevel('k1','k2')

Ohio     Colorado
      green red    green
k2 k1                   
1  a      0   1        2
2  a      3   4        5
3  a      6   7        8
1  b      9  10       11
2  b     12  13       14
1  c     15  16       17

In [136]:
df.swaplevel('k1','k2').loc[1]

Ohio     Colorado
   green red    green
k1                   
a      0   1        2
b      9  10       11
c     15  16       17

In [137]:
df.query('k2==1')

Ohio     Colorado
      green red    green
k1 k2                   
a  1      0   1        2
b  1      9  10       11
c  1     15  16       17

# merge

In [138]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],
                   'data1' : range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [140]:
df2 = pd.DataFrame({'key':['a','b','d'],
                   'data2':range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [142]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

# merge on index

In [143]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],
                     'value':range(6)})
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [147]:
right1 = pd.DataFrame({'group_val':[3.5,7]},index=['a','b'])
right1

group_val
a        3.5
b        7.0

In [148]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [149]:
import getpass

In [154]:
user = getpass.getuser()
user

'shaojun'

In [155]:

p = getpass.getpass()
p

········


'abcd'

In [156]:
!pwd

/Users/shaojun/projects/coupon/experimental/ab
