In [42]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [43]:
names.shape

(7,)

In [44]:
data = np.random.randn(7,4)
data

array([[-0.43739493, -0.0165754 ,  0.01044052,  0.0436514 ],
       [-0.09701393, -1.59373532,  1.30073534, -0.22902381],
       [ 0.567108  , -1.92591423,  0.69055679,  0.98758835],
       [ 0.65921086,  1.56186157,  0.46700166,  0.96239861],
       [ 0.23146589,  0.35652543,  0.43446653, -0.87645715],
       [ 0.49422724, -1.975238  , -0.77509654, -0.69588709],
       [ 1.19111136,  1.22813515,  0.49882419,  0.42367307]])

In [45]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [46]:
data[names == 'bob']

array([[-0.43739493, -0.0165754 ,  0.01044052,  0.0436514 ],
       [ 0.65921086,  1.56186157,  0.46700166,  0.96239861]])

In [83]:
names_bool = np.array([True, False, False,  True, False, False, False])
names_bool

array([ True, False, False,  True, False, False, False])

In [84]:
names_bool == False

array([False,  True,  True, False,  True,  True,  True])

In [85]:
~names_bool

array([False,  True,  True, False,  True,  True,  True])

In [89]:
~names_bool

array([False,  True,  True, False,  True,  True,  True])

In [91]:
a = pd.DataFrame(names_bool)
a

0
0   True
1  False
2  False
3   True
4  False
5  False
6  False

In [92]:
~a

0
0  False
1   True
2   True
3  False
4   True
5   True
6   True

In [95]:
a = a.astype(int)
a

0
0  1
1  0
2  0
3  1
4  0
5  0
6  0

In [96]:
~a

0
0 -2
1 -1
2 -1
3 -2
4 -1
5 -1
6 -1

In [97]:
1-a

0
0  0
1  1
2  1
3  0
4  1
5  1
6  1

In [104]:
b = a.astype('bool')
b

0
0   True
1  False
2  False
3   True
4  False
5  False
6  False

In [106]:
b.columns

RangeIndex(start=0, stop=1, step=1)

In [115]:
print(b.to_numpy().T[0])

[ True False False  True False False False]


In [116]:
data[b.to_numpy().T[0]]

array([[-1.52738466,  0.42196656,  0.3888152 , -0.14597536],
       [-1.83111953,  1.71128051, -0.64349322,  0.49794524]])

In [ ]:
data[a]

In [51]:
data[~names_bool]

array([[-0.09701393, -1.59373532,  1.30073534, -0.22902381],
       [ 0.567108  , -1.92591423,  0.69055679,  0.98758835],
       [ 0.23146589,  0.35652543,  0.43446653, -0.87645715],
       [ 0.49422724, -1.975238  , -0.77509654, -0.69588709],
       [ 1.19111136,  1.22813515,  0.49882419,  0.42367307]])

In [56]:
data[(names == 'bob') | (names == 'joe')]

array([[-0.43739493, -0.0165754 ,  0.01044052,  0.0436514 ],
       [-0.09701393, -1.59373532,  1.30073534, -0.22902381],
       [ 0.65921086,  1.56186157,  0.46700166,  0.96239861],
       [ 0.49422724, -1.975238  , -0.77509654, -0.69588709],
       [ 1.19111136,  1.22813515,  0.49882419,  0.42367307]])

In [117]:
data

array([[-1.52738466,  0.42196656,  0.3888152 , -0.14597536],
       [-1.53055881, -1.43045225, -0.26572542,  0.95567306],
       [ 1.17813075,  1.40977111, -0.01659027,  0.75297846],
       [-1.83111953,  1.71128051, -0.64349322,  0.49794524],
       [-0.24192235, -1.68310746,  0.42728046,  1.30103078],
       [ 1.06961656, -0.63197014,  0.36700172,  0.97541148],
       [-1.8041003 , -0.21546819,  1.54910145, -0.35188179]])

In [120]:
data[0,1]

0.42196655924029275

In [121]:
data[0]

array([-1.52738466,  0.42196656,  0.3888152 , -0.14597536])

In [122]:
data[[0,1]]

array([[-1.52738466,  0.42196656,  0.3888152 , -0.14597536],
       [-1.53055881, -1.43045225, -0.26572542,  0.95567306]])

In [123]:
data[:,[0,1]]

array([[-1.52738466,  0.42196656],
       [-1.53055881, -1.43045225],
       [ 1.17813075,  1.40977111],
       [-1.83111953,  1.71128051],
       [-0.24192235, -1.68310746],
       [ 1.06961656, -0.63197014],
       [-1.8041003 , -0.21546819]])

In [57]:
z = data[(names == 'bob') & (names == 'joe')]

In [58]:
z.shape

(0, 4)

In [59]:
data > 0

array([[False, False,  True,  True],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [ True,  True,  True,  True]])

In [60]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.01044052, 0.0436514 ],
       [0.        , 0.        , 1.30073534, 0.        ],
       [0.567108  , 0.        , 0.69055679, 0.98758835],
       [0.65921086, 1.56186157, 0.46700166, 0.96239861],
       [0.23146589, 0.35652543, 0.43446653, 0.        ],
       [0.49422724, 0.        , 0.        , 0.        ],
       [1.19111136, 1.22813515, 0.49882419, 0.42367307]])

In [61]:
data

array([[0.        , 0.        , 0.01044052, 0.0436514 ],
       [0.        , 0.        , 1.30073534, 0.        ],
       [0.567108  , 0.        , 0.69055679, 0.98758835],
       [0.65921086, 1.56186157, 0.46700166, 0.96239861],
       [0.23146589, 0.35652543, 0.43446653, 0.        ],
       [0.49422724, 0.        , 0.        , 0.        ],
       [1.19111136, 1.22813515, 0.49882419, 0.42367307]])

In [62]:
data = np.random.randn(7,4)
data

array([[-1.52738466,  0.42196656,  0.3888152 , -0.14597536],
       [-1.53055881, -1.43045225, -0.26572542,  0.95567306],
       [ 1.17813075,  1.40977111, -0.01659027,  0.75297846],
       [-1.83111953,  1.71128051, -0.64349322,  0.49794524],
       [-0.24192235, -1.68310746,  0.42728046,  1.30103078],
       [ 1.06961656, -0.63197014,  0.36700172,  0.97541148],
       [-1.8041003 , -0.21546819,  1.54910145, -0.35188179]])

In [63]:
data[[4,3,2,1]]

array([[-0.24192235, -1.68310746,  0.42728046,  1.30103078],
       [-1.83111953,  1.71128051, -0.64349322,  0.49794524],
       [ 1.17813075,  1.40977111, -0.01659027,  0.75297846],
       [-1.53055881, -1.43045225, -0.26572542,  0.95567306]])

In [68]:
df = pd.DataFrame(data, columns=('0','1','2','3'))

In [69]:
df

0         1         2         3
0 -1.527385  0.421967  0.388815 -0.145975
1 -1.530559 -1.430452 -0.265725  0.955673
2  1.178131  1.409771 -0.016590  0.752978
3 -1.831120  1.711281 -0.643493  0.497945
4 -0.241922 -1.683107  0.427280  1.301031
5  1.069617 -0.631970  0.367002  0.975411
6 -1.804100 -0.215468  1.549101 -0.351882

In [70]:
df[['3','2']]

3         2
0 -0.145975  0.388815
1  0.955673 -0.265725
2  0.752978 -0.016590
3  0.497945 -0.643493
4  1.301031  0.427280
5  0.975411  0.367002
6 -0.351882  1.549101

In [75]:
arr = np.arange(16).reshape(2,2,4)

In [76]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [77]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [78]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [79]:
arr.transpose([1,0,2])

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [80]:
arr.transpose([2,0,1])

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [81]:
arr.transpose([0,2,1])

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [82]:
arr.transpose([0,2,1]).reshape(16,)

array([ 0,  4,  1,  5,  2,  6,  3,  7,  8, 12,  9, 13, 10, 14, 11, 15])

In [ ]:
pwd

In [1]:
!pwd

/Users/shaojun/projects/coupon/experimental/ab
